name: Feature Request
description: Proposer une nouvelle fonctionnalité
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Merci de proposer une nouvelle fonctionnalité ! ✨

  - type: textarea
    id: problem
    attributes:
      label: Problème / Besoin
      description: Quel problème cette fonctionnalité résout-elle ?
      placeholder: |
        Actuellement, il n'est pas possible de...
        Ce serait utile pour...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      description: Décrivez la fonctionnalité souhaitée
      placeholder: |
        Ajouter un bouton pour...
        Implémenter un système de...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considérées
      description: Avez-vous pensé à d'autres solutions ?
      placeholder: On pourrait aussi...

  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options:
        - Haute (bloquant)
        - Moyenne (important)
        - Basse (nice to have)
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Module concerné
      options:
        - Core (Simulation)
        - Network (Graphes)
        - Visualization (Interface)
        - Data (OSM, Tuiles)
        - Utils
        - Documentation
        - Autre

  - type: textarea
    id: context
    attributes:
      label: Contexte additionnel
      description: Maquettes, liens, exemples...
      placeholder: Voir cet exemple...
